/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreauditResultRouteImport } from './routes/preaudit-result'
import { Route as AuditResultRouteImport } from './routes/audit-result'
import { Route as AuditIntakeRouteImport } from './routes/audit-intake'
import { Route as IndexRouteImport } from './routes/index'

const PreauditResultRoute = PreauditResultRouteImport.update({
  id: '/preaudit-result',
  path: '/preaudit-result',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditResultRoute = AuditResultRouteImport.update({
  id: '/audit-result',
  path: '/audit-result',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIntakeRoute = AuditIntakeRouteImport.update({
  id: '/audit-intake',
  path: '/audit-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-intake': typeof AuditIntakeRoute
  '/audit-result': typeof AuditResultRoute
  '/preaudit-result': typeof PreauditResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-intake': typeof AuditIntakeRoute
  '/audit-result': typeof AuditResultRoute
  '/preaudit-result': typeof PreauditResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-intake': typeof AuditIntakeRoute
  '/audit-result': typeof AuditResultRoute
  '/preaudit-result': typeof PreauditResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audit-intake' | '/audit-result' | '/preaudit-result'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audit-intake' | '/audit-result' | '/preaudit-result'
  id: '__root__' | '/' | '/audit-intake' | '/audit-result' | '/preaudit-result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditIntakeRoute: typeof AuditIntakeRoute
  AuditResultRoute: typeof AuditResultRoute
  PreauditResultRoute: typeof PreauditResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preaudit-result': {
      id: '/preaudit-result'
      path: '/preaudit-result'
      fullPath: '/preaudit-result'
      preLoaderRoute: typeof PreauditResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-result': {
      id: '/audit-result'
      path: '/audit-result'
      fullPath: '/audit-result'
      preLoaderRoute: typeof AuditResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-intake': {
      id: '/audit-intake'
      path: '/audit-intake'
      fullPath: '/audit-intake'
      preLoaderRoute: typeof AuditIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditIntakeRoute: AuditIntakeRoute,
  AuditResultRoute: AuditResultRoute,
  PreauditResultRoute: PreauditResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
